'use client'

import React, { useState, useRef } from 'react'
import { Card, Button, Input, addToast, cn, Checkbox } from '@heroui/react'
import Icon from '@/components/icon'
import { useRouter, useSearchParams } from 'next/navigation'
import { api } from '@/api/generated/main-service'
import { ProChip } from '@/components/docs/DocComponents'

export default function CreateTemplatePage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const projectId = searchParams.get('projectId')

  const [templateName, setTemplateName] = useState('')
  const [templateKey, setTemplateKey] = useState('')
  const [uploadedFile, setUploadedFile] = useState<File | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [isGeneratingKey, setIsGeneratingKey] = useState(false)
  const [isDragOver, setIsDragOver] = useState(false)
  const [showErrors, setShowErrors] = useState(false)
  const [autoGeneratedVariable, setAutoGeneratedVariable] = useState(true)

  const fileInputRef = useRef<HTMLInputElement>(null)

  const generateKey = async () => {
    setIsGeneratingKey(true)
    try {
      const key = await api.templates.templateGenerateKeyList()
      setTemplateKey(key)
    } catch (error) {
      console.error('Failed to generate key', error)
      addToast({
        title: 'Error',
        description: 'Failed to generate template key',
        color: 'danger'
      })
    } finally {
      setIsGeneratingKey(false)
    }
  }

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0]
      validateAndSetFile(file)
    }
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragOver(false)
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0]
      validateAndSetFile(file)
    }
  }

  const validateAndSetFile = (file: File) => {
    const validExtensions = ['.docx']
    const fileExtension = '.' + file.name.split('.').pop()?.toLowerCase()

    if (!validExtensions.includes(fileExtension)) {
      addToast({
        title: 'Invalid file type',
        description: 'Please upload a .docx file only',
        color: 'danger'
      })
      return
    }

    setUploadedFile(file)
  }

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragOver(true)
  }

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragOver(false)
  }

  const clearFile = () => {
    setUploadedFile(null)
    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
  }

  const handleCreate = async () => {
    if (!uploadedFile || !templateName) {
      setShowErrors(true)
      addToast({
        title: 'Validation Error',
        description: 'Please fill in all required fields',
        color: 'danger'
      })
      return
    }

    setIsLoading(true)
    try {
      const response = await api.templates.templatesCreate(
        {
          name: templateName,
          templateKey: templateKey || undefined,
          project_id: projectId || undefined,
          isAutoGeneratedVariable: autoGeneratedVariable
        },
        { file: uploadedFile }
      )

      if (response && response.templateKey) {
        router.replace(`/pdf/templates/${response.templateKey}${projectId ? `?projectId=${projectId}` : ''}`)
      } else {
        goBack()
      }
    } catch (error) {
      console.error('Failed to create template', error)
      addToast({
        title: 'Failed to create template',
        description: 'Please try again',
        color: 'danger'
      })
    }
  }

  const goBack = () => {
    if (projectId) {
      router.push(`/project/${projectId}/pdf-templates`)
    } else {
      router.back()
    }
  }

  return (
    <div className='mx-auto max-w-2xl py-4'>
      <div className='mb-4'>
        <button
          onClick={goBack}
          className='mb-2 flex items-center gap-2 text-sm font-medium text-default-500 transition-colors hover:text-foreground'>
          <Icon icon='lucide:arrow-left' className='h-4 w-4' />
          Back to Templates
        </button>
        <h1 className='mt-4 text-2xl font-bold tracking-tight text-foreground'>Create New PDF Template</h1>
        <p className='text-sm text-default-500'>Upload your template file and configure the basic settings</p>
      </div>

      <div className='flex flex-col gap-4'>
        {/* Step 1: Upload */}
        <Card className='border border-default-200 shadow-sm' radius='none'>
          <div className='p-5'>
            <div className='mb-3 flex items-center justify-between'>
              <h2 className='text-base font-bold uppercase tracking-tight text-foreground'>1. Upload Template File</h2>
              {uploadedFile && (
                <span className='flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-primary'>
                  <Icon icon='lucide:check-circle-2' className='h-4 w-4' />
                  Uploaded
                </span>
              )}
            </div>

            {/* Dropzone */}
            <div
              className={cn(
                'relative flex min-h-[160px] cursor-pointer flex-col items-center justify-center border-2 border-dashed p-6 transition-all duration-200',
                isDragOver
                  ? 'border-primary bg-primary-50'
                  : showErrors && !uploadedFile
                    ? 'border-danger bg-danger-50'
                    : uploadedFile
                      ? 'border-primary/50 bg-content2'
                      : 'border-default-300 bg-content2 hover:border-primary hover:bg-primary-50/30',
                isLoading && 'pointer-events-none opacity-50'
              )}
              onDrop={!isLoading ? handleDrop : undefined}
              onDragOver={!isLoading ? handleDragOver : undefined}
              onDragLeave={!isLoading ? handleDragLeave : undefined}
              onClick={() => !isLoading && fileInputRef.current?.click()}>
              <input ref={fileInputRef} type='file' className='hidden' accept='.docx' onChange={handleFileChange} />

              {uploadedFile ? (
                <div className='flex flex-col items-center text-center'>
                  <div className='mb-3 flex h-12 w-12 items-center justify-center border border-primary bg-primary text-primary-foreground shadow-sm'>
                    <Icon icon='lucide:file-check' className='h-6 w-6' />
                  </div>
                  <p className='text-base font-bold text-foreground'>{uploadedFile.name}</p>
                  <p className='text-xs font-medium text-default-500'>{(uploadedFile.size / 1024).toFixed(2)} KB</p>
                  <button
                    onClick={e => {
                      e.stopPropagation()
                      clearFile()
                    }}
                    disabled={isLoading}
                    className='mt-3 flex items-center gap-1.5 text-xs font-bold uppercase tracking-wide text-default-400 hover:text-danger disabled:pointer-events-none disabled:opacity-50'>
                    <Icon icon='lucide:x' className='h-3.5 w-3.5' />
                    Remove File
                  </button>
                </div>
              ) : (
                <>
                  <div className='mb-4 flex h-16 w-16 items-center justify-center border border-default-200 bg-background shadow-sm'>
                    <Icon icon='lucide:upload-cloud' className='h-8 w-8 text-default-400' />
                  </div>
                  <div className='text-center'>
                    <p className='text-lg font-bold text-foreground'>Click to upload or drag and drop</p>
                    <p className='mt-1 text-xs font-medium text-default-500'>DOCX files only</p>
                  </div>
                </>
              )}
            </div>

            <div className='mt-4 flex flex-col gap-2'>
              <Checkbox
                isSelected={autoGeneratedVariable}
                onValueChange={setAutoGeneratedVariable}
                isDisabled={isLoading}>
                <div className='flex flex-col items-start'>
                  <div className='flex items-center gap-1'>
                    <span className='text-sm text-foreground'>Auto-detect variables from file</span>
                    <ProChip />
                  </div>
                  <span className='text-xs text-default-500'>
                    Scan the document for variables {`{{name}}`} and add them to the builder automatically.
                  </span>
                </div>
              </Checkbox>
            </div>
          </div>
        </Card>

        {/* Step 2: Config */}
        <Card className='border border-default-200 shadow-sm' radius='none'>
          <div className='p-5'>
            <h2 className='mb-5 text-base font-bold uppercase tracking-tight text-foreground'>
              2. Template Configuration
            </h2>

            <div className='space-y-5'>
              <div className='grid gap-5 md:grid-cols-2'>
                <div className='space-y-2'>
                  <label className='flex h-5 items-center text-[10px] font-bold uppercase tracking-wider text-default-500'>
                    Template Name <span className='text-danger'>*</span>
                  </label>
                  <Input
                    size='md'
                    variant='bordered'
                    radius='none'
                    placeholder='e.g. Monthly Invoice 2024'
                    value={templateName}
                    onValueChange={setTemplateName}
                    isInvalid={showErrors && !templateName}
                    errorMessage={showErrors && !templateName ? 'Template name is required' : ''}
                    isDisabled={isLoading}
                    classNames={{
                      input: 'font-medium',
                      inputWrapper: 'border-default-300 group-data-[focus=true]:border-primary shadow-none'
                    }}
                  />
                </div>

                <div className='space-y-2'>
                  <label className='flex h-5 items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-default-500'>
                    Template Key
                    <span className='bg-content3 px-1 py-0.5 text-[9px] font-bold text-default-600'>UNIQUE ID</span>
                  </label>
                  <div className='flex gap-2'>
                    <Input
                      size='md'
                      variant='bordered'
                      radius='none'
                      placeholder='Optional'
                      value={templateKey}
                      onValueChange={setTemplateKey}
                      isDisabled={isLoading}
                      classNames={{
                        input: 'font-mono text-xs',
                        inputWrapper: 'border-default-300 group-data-[focus=true]:border-primary shadow-none'
                      }}
                    />
                    <Button
                      size='md'
                      variant='flat'
                      radius='none'
                      onPress={generateKey}
                      isIconOnly
                      isLoading={isGeneratingKey}
                      isDisabled={isLoading}
                      className='shrink-0 bg-content3 text-default-600 hover:bg-default-200'>
                      {!isGeneratingKey && <Icon icon='lucide:sparkles' className='h-4 w-4' />}
                    </Button>
                  </div>
                </div>
              </div>

              <div className='flex items-center justify-end gap-3 border-t border-default-100 pt-4'>
                <Button
                  size='md'
                  variant='light'
                  radius='none'
                  onPress={() => router.back()}
                  isDisabled={isLoading}
                  className='font-bold uppercase tracking-wide text-default-500 hover:text-foreground'>
                  Cancel
                </Button>
                <Button
                  color='primary'
                  size='md'
                  radius='none'
                  onPress={handleCreate}
                  isLoading={isLoading}
                  startContent={!isLoading && <Icon icon='lucide:plus' className='h-4 w-4' />}
                  className='px-6 font-bold uppercase tracking-wide shadow-none'>
                  Create Template
                </Button>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </div>
  )
}
